name: superheroes
description: Search for superheroes on superheroapi.com

publish_to: 'none'
version: 1.0.2+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  rxdart: ^0.27.4
  provider: ^6.0.3
  google_fonts: ^3.0.1
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.5.0
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  network_image_mock: ^2.1.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  golden_toolkit: ^0.13.0


flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/images/
    - assets/icons/
    - .env
